### ISSUE TITLE
In PGC: polyinterface not found.

### ISSUE THREAD

**Issue by mkohanim** [jamespauly/udi-daikin-poly#5]
Traceback (most recent call last):
    import polyinterface
  File "./daikin-poly.py", line 2, in <module>
ModuleNotFoundError: No module named 'polyinterface'

**Comment by jamespauly** [comment]
Hey Michel,

Are you having this issue locally?

Also wanted to talk to you to see if there was a way to do custom icons on the ISY?  I know this would pose the issue of how would you install on someone else's ISY if from your polyglot code.

Regards,
James

**Comment by mkohanim** [comment]
Hi James,

Thank you very much for getting  back. No, this is PGC only. By ISY icons, do you mean the icon for your node server? If so, yes, you can define it in the NLS file. If not, please elaborate.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jamespauly** [comment]
That’s strange let me look at it.  The polyInterface should be pre-loaded on PGC.

As for the icons I’m mean if you didn’t want to use one of the defaults one’s on the ISY could you upload one onto the ISY?  This really is not needed this was more curiosity.  I’m guessing no.

Regards,
James

From: Michel Kohanim ***@***.***>
Reply-To: jamespauly/udi-daikin-poly ***@***.***>
Date: Wednesday, August 18, 2021 at 6:14 PM
To: jamespauly/udi-daikin-poly ***@***.***>
Cc: James Paul ***@***.***>, Comment ***@***.***>
Subject: Re: [jamespauly/udi-daikin-poly] In PGC: polyinterface not found. (#5)

ATTENTION: This email was sent from outside the company. Do not click links or open files unless you know it is safe. Forward malicious emails to ***@***.***

Hi James,

Thank you very much for getting back. No, this is PGC only. By ISY icons, do you mean the icon for your node server? If so, yes, you can define it in the NLS file. If not, please elaborate.

With kind regards,

******************************
Michel Kohanim
CEO

(p) 818.631.0333
http://www.universal-devices.com<http://www.universal-devices.com/><https://urldefense.com/v3/__http:/www.universal-devices.com*3Chttp:/*www.universal-devices.com/*3E__;JS8l!!BiPlgCE7GXGj!nt-kvysJVN-SkdczcgWITuSGhEYNrwvaHQlNLnxkSvRtlicnj900qlqIISugKj2V$>
******************************

**Comment by jamespauly** [comment]
Urg.  I see the issue I messed it up when I was redoing it for PGC v3.  I removed the pgc_interface when deployed to the cloud.  I'll fix it and let you know.

Regards,
James

**Comment by mkohanim** [comment]
Thank you very very much!

With kind regards,

******************************
Michel Kohanim

(p) 818.631.0333
http://www.universal-devices.com
******************************

________________________________

**Comment by jamespauly** [comment]
Michel,

Try it again and let me know.  I have this in both PGC 2 and PGC 3 and currently I'm doing improvements on the PGC 3 code.  So it won't let me install unless I uninstall to test the install unless I first uninstall my PGC 3 instance.  I guess I should name them differently.  It should work now but let me know.  Also the PGC 3 code is much cleaner.  I'm also about ready to release a version where you set all Daikin mini split node's at the same time.

**Comment by mkohanim** [comment]
Hi James, thank you very much. I still get the error below. Also, what you mean by "mini split nodes" ?


2021-08-19 15:52:16,968 [MainThread] [INFO ] PGC Interface 1.1.9 Starting...

2021-08-19 15:52:17,570 [MainThread] [ERROR] Traceback (most recent call last):

2021-08-19 15:52:17,570 [MainThread] [ERROR] File "./daikin-poly.py", line 10, in <module>

2021-08-19 15:52:17,572 [MainThread] [ERROR] from nodes import DaikinController

2021-08-19 15:52:17,572 [MainThread] [ERROR] from .DaikinController      import DaikinController

2021-08-19 15:52:17,572 [MainThread] [ERROR] File "/app/nodeserver/nodes/DaikinController.py", line 12, in <module>

2021-08-19 15:52:17,573 [MainThread] [ERROR] LOG_HANDLER.set_log_format('%(asctime)s %(threadName)-10s %(name)-18s %(levelname)-8s %(module)s:%(funcName)s: %(message)s')

2021-08-19 15:52:17,573 [MainThread] [ERROR] NameError

2021-08-19 15:52:17,572 [MainThread] [ERROR] File "/app/nodeserver/nodes/__init__.py", line 5, in <module>

2021-08-19 15:52:17,573 [MainThread] [ERROR] name 'LOG_HANDLER' is not defined

2021-08-19 15:52:17,573 [MainThread] [ERROR] :



With kind regards,



******************************

  Michel Kohanim

             CEO



  (p) 818.631.0333

  http://www.universal-devices.com<http://www.universal-devices.com/>

******************************


________________________________
